var url = "https://www.imooc.com/course/ajaxlist";
var page = 0;
var page_size = 5;
var sort = "last";
var is_easy = 0;
var lange_id = 0;
var pos_id = 0;
var unlearn = 0;


// 请求数据
var loadMore = function (that) {
    that.setData({
        hidden: false
    });
    wx.request({
        url: url,
        data: {
            page: page,
            page_size: page_size,
            sort: sort,
            is_easy: is_easy,
            lange_id: lange_id,
            pos_id: pos_id,
            unlearn: unlearn
        },
        success: function (res) {
            //console.info(that.data.list);
            var list = that.data.list;
            for (var i = 0; i < res.data.list.length; i++) {
                list.push(res.data.list[i]);
            }
            that.setData({
                list: list
            });
            page++;
            that.setData({
                hidden: true
            });
        }
    });
}
Page({
    data: {
        hidden: true,
        list: [{
                "id": "1425",
                "name": "鸿蒙NEXT应用开发指南",
                "pic": "66387ad3093699d105400304",
                "cat_id": "3",
                "duration": "4200",
                "teacher_id": "6008309",
                "start_time": "1714838400",
                "end_time": "2061993600",
                "create_time": "1714977521",
                "status": "3",
                "short_description": "2024年务必抓住的职业“薪”机遇，抢占先机",
                "description": "随着鸿蒙生态系统不断完善和市场份额持续增长，移动互联网公司近半数已经启动鸿蒙开发。同时，企业急聘鸿蒙人才，市场需求猛增。 \r\n\r\n据《2024年春招市场行情周报（第一期）》报告显示，春节后开工第一周，鸿蒙相关职位数同比增长163%，投递人数同比增长349%，即分别增至去年同期的2.6倍、4.5倍，涨势突出。 \r\n\r\n鸿蒙开发岗的平均招聘薪资水平达到18191元/月，比总体开发岗的平均薪资（16617元/月）高出9%。无论是对于计算机专业相关的毕业生还是正在求职的程序员来说，这样的薪资水平都是具有相当的诱惑力的，同时也从侧面体现出招聘企业们对于鸿蒙发展前景的看好和重视。 \r\n\r\n对于程序员来说，选择鸿蒙，在就业前景这方面可以说是一片新蓝海。正如前面的数据所呈现的，鸿蒙相关的岗位不仅需求量大，而且一直是增长的态势，说明这一领域正处于发展的上升阶段，生态发展的红利不可估量，前景自然大好。 \r\n\r\n我们特邀具有移动端开发经验15年、华为HarmonyOS高级认证开发者——Jett老师，来带你体验《万物互联时代全新技术——轻松实现华为鸿蒙1+8+N技术》 \r\n\r\n只要你对鸿蒙感兴趣，想了解鸿蒙知识、体验鸿蒙技术，都欢迎你来参与该课程！相信你一定能收获满满！",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "具备一定的编程基础",
                "purpose": "1、为何全国互联网大厂集体加入鸿蒙生态发展\r\n\r\n2、鸿蒙生态开发对开发人员的意义\r\n\r\n3、纯血版鸿蒙技术面分析\r\n\r\n4、实战鸿蒙1+8+N核心技术实现",
                "video_id": "0",
                "numbers": "426",
                "update_time": "1715131882",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "1",
                "teach_type": "1",
                "course_type": "1",
                "keyword": null,
                "finished": "0",
                "uid": "100120",
                "chapter_media": "1-4",
                "online_time": "1715130947",
                "blur_pic": "66387ad4000131ca05400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "0",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover001",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "66387ad3093699d100000000",
                "app_cover_pic": "66387adc09761e3302160304",
                "max_chapter": "1",
                "max_media": "4",
                "duration_fmt": "1小时10分钟",
                "pic_url": "//img1.sycdn.imooc.com/66387ad3093699d105400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "入门",
                "media_total": "5"
            },
            {
                "id": "1426",
                "name": "AI岗位就业指南：剖析企业需求，展现个人优势",
                "pic": "66387c290962e6a505400304",
                "cat_id": "63",
                "duration": "6000",
                "teacher_id": "6002955",
                "start_time": "1714838400",
                "end_time": "2061993600",
                "create_time": "1714977879",
                "status": "3",
                "short_description": "AI岗位就业指南：剖析企业需求，展现个人优势",
                "description": "随着AI技术越来越广泛的应用，各地区、各行业陆续开始吸纳相关人才，多个大厂也扩编了对应的岗位，AI方向就业机会与日俱增。 \r\n\r\n初涉AI就业市场的同学常有疑惑：\r\n\r\nØ  AI行业岗位地如何划分的？\r\n\r\nØ  想要胜任相关的工作要具备哪些能力？\r\n\r\nØ  如何优化简历？ \r\n\r\n为此，资深AI工程师言有三老师，帮助的大家全面解读AI行业岗位划分与人才需求，助力AI人才就业。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "学生、研究人员、工程师、数据科学家等对自然语言处理和人工智能感兴趣的人群",
                "purpose": "Ø  AI行业岗位地如何划分的？\r\n\r\nØ  想要胜任相关的工作要具备哪些能力？\r\n\r\nØ  如何优化简历？",
                "video_id": "0",
                "numbers": "562",
                "update_time": "1715131865",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "1",
                "teach_type": "1",
                "course_type": "1",
                "keyword": null,
                "finished": "0",
                "uid": "100120",
                "chapter_media": "1-5",
                "online_time": "1715130898",
                "blur_pic": "66387c2a0001839605400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "0",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover001",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "663ad37d0940885c05400304",
                "app_cover_pic": "66387c3b094b5cef02160304",
                "max_chapter": "1",
                "max_media": "5",
                "duration_fmt": "1小时40分钟",
                "pic_url": "//img1.sycdn.imooc.com/66387c290962e6a505400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "入门",
                "media_total": "5"
            },
            {
                "id": "1424",
                "name": "探索奥秘，玩转大语言模型",
                "pic": "66384815092548df05400304",
                "cat_id": "63",
                "duration": "2460",
                "teacher_id": "11280240",
                "start_time": "1714838400",
                "end_time": "2062166400",
                "create_time": "1714964758",
                "status": "3",
                "short_description": "快来和AI大佬Eric老师一起揭开大语言模型的奥秘！不容错过的科学盛宴!",
                "description": "AI时代，大语言模型正在引领技术和应用的革新！大语言模型作为当前人工智能领域的热门话题，通过了解大语言模型领域的知识和应用，进一步提升深入学习的兴趣和需求。对于想要深入学习和应用大语言模型的同学来说，本课程是一个了解其重要性和前沿发展的必要环节。\r\nEric带大家一探大语言模型背后的奥秘，可以收获大语言模型的技术细节和背后故事，对于大语言模型应用中遇到的问题，掌握相应解决方案，扩宽技术水平，提升解决问题的能力。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "对大模型有了解的人群，想进入大模型行业的人群，先转行到大模型的人群。",
                "purpose": "Ø 解读｜大语言模型的原理和技术细节\r\n\r\nØ 直击｜大语言模型发展的重要性和应用场景\r\n\r\nØ 发展｜大语言模型发展趋势和前沿研究方向\r\n\r\nØ 突破｜案例实践助力拓展技术与能力提升",
                "video_id": "0",
                "numbers": "344",
                "update_time": "1714976385",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "1",
                "teach_type": "1",
                "course_type": "1",
                "keyword": null,
                "finished": "0",
                "uid": "3200030",
                "chapter_media": "6-1",
                "online_time": "1714976333",
                "blur_pic": "6638481600013c1e05400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "0",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover001",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "66384815092548df00000000",
                "app_cover_pic": "6638481f096c296a02160304",
                "max_chapter": "6",
                "max_media": "1",
                "duration_fmt": "41分钟",
                "pic_url": "//img1.sycdn.imooc.com/66384815092548df05400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "入门",
                "media_total": "8"
            },
            {
                "id": "1423",
                "name": "AI时代下，前端工程师的生存与发展策略",
                "pic": "6638428c0959bfec05400304",
                "cat_id": "3",
                "duration": "6000",
                "teacher_id": "2432190",
                "start_time": "1714838400",
                "end_time": "2072793600",
                "create_time": "1714963351",
                "status": "3",
                "short_description": "AI时代下，前端工程师的生存与发展策略",
                "description": "ChatGPT都能写代码了，你怎么还敢躺平？\r\n\r\n前端技术发展迅猛，对程序员的要求也就越来越高，行业变革既是挑战，也是机遇，是做大浪中的弄潮儿，还是在被后浪拍在沙滩上，主动权在自己手中。\r\n为了帮助前端同学们更好的了解行业、掌握就业主动权、拓宽收入渠道，我们特意邀请了站内合作的金牌讲师Brian老师，给大家带来干货满满的前端提升课程。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "1.对前端感兴趣、想入门或有提升想法的学员\r\n2.具备一定的编程基础",
                "purpose": "1、前端初学者可了解就业前景与策略，为职业发展做准备；\r\n2、专业前端工程师可了解新趋势与技术融合，突破瓶颈，提升效率；\r\n3、对AI在前端应用感兴趣的开发者，可学习AI提升开发效率及实用工具实操方法。",
                "video_id": "0",
                "numbers": "267",
                "update_time": "1715013793",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "1",
                "teach_type": "1",
                "course_type": "1",
                "keyword": null,
                "finished": "0",
                "uid": "3200030",
                "chapter_media": "1-5",
                "online_time": "1714976156",
                "blur_pic": "6638428c000173d805400304",
                "satisfied_score": "8.7",
                "ctype_one": "1",
                "ctype_one_score": "6.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "1",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover001",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "6638428c0959bfec00000000",
                "app_cover_pic": "6638429309b3f27c02160304",
                "max_chapter": "1",
                "max_media": "5",
                "duration_fmt": "1小时40分钟",
                "pic_url": "//img1.sycdn.imooc.com/6638428c0959bfec05400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "入门",
                "media_total": "5"
            },
            {
                "id": "1417",
                "name": "徐老师带你新一代分布式调度工具-DolphinScheduler",
                "pic": "66052ae309f7e7a005400304",
                "cat_id": "46",
                "duration": "11220",
                "teacher_id": "7861049",
                "start_time": "1711468800",
                "end_time": "1934899200",
                "create_time": "1711614835",
                "status": "3",
                "short_description": "带你认识一款分布式、去中心化、易扩展的可视化DAG工作流任务调度平台。",
                "description": "本课程针对新一代分布式调度工具DolphinScheduler(中文名：海豚调度)进行讲解，主要涉及DolphinScheduler的原理架构，以及丰富的案例实战（包括大数据中的常见任务类型：Shell脚本、Hive SQL、Spark任务、Flink任务等）。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "了解Shell、Hive、Spark、Flink基础操作学习效果更佳",
                "purpose": "1：快速了解DolphinScheduler的核心原理及架构；\r\n2：掌握DolphinScheduler的安装部署；\r\n3：掌握Shell任务、HiveSQL任务、Spark任务、Flink任务在DolphinScheduler中的调度。",
                "video_id": "0",
                "numbers": "721",
                "update_time": "1711677245",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "3",
                "teach_type": "2",
                "course_type": "3",
                "keyword": null,
                "finished": "0",
                "uid": "106515",
                "chapter_media": "3-10",
                "online_time": "1711677268",
                "blur_pic": "66052ae40001c17205400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "0",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover037",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "66052aea092e6fe105400304",
                "app_cover_pic": "66052b6e096befa602160304",
                "max_chapter": "3",
                "max_media": "10",
                "duration_fmt": "3小时7分钟",
                "pic_url": "//img1.sycdn.imooc.com/66052ae309f7e7a005400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "中级",
                "media_total": "15"
            },
            {
                "id": "1416",
                "name": "徐老师带你入门新一代流式数据湖新秀--Apache Paimon",
                "pic": "65f7ae6f0932456505400304",
                "cat_id": "46",
                "duration": "7800",
                "teacher_id": "7861049",
                "start_time": "1710259200",
                "end_time": "1932652800",
                "create_time": "1710730921",
                "status": "3",
                "short_description": "带你认识新一代流式数据湖新秀，如何为构建湖仓一体架构提供底层技术支撑",
                "description": "本课程针对新一代流式数据湖技术组件Apache Paimon进行讲解，主要涉及Paimon的原理架构、基于Flink SQL读写Paimon，以及Paimon中不同表类型的应用。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "了解Scala基础语法、Flink基本操作，学习效果更佳",
                "purpose": "1：快速了解Paimon的核心原理及架构；\r\n2：掌握Flink SQL如何读写Paimon中的数据；\r\n3：掌握Paimon中内部表、外部表、分区表和临时表的典型应用场景。",
                "video_id": "0",
                "numbers": "574",
                "update_time": "1710749711",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "3",
                "teach_type": "2",
                "course_type": "3",
                "keyword": null,
                "finished": "0",
                "uid": "106515",
                "chapter_media": "3-5",
                "online_time": "1710749649",
                "blur_pic": "65f7ae700001e59f05400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "0",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover017",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "65f7ae750984d7bd05400304",
                "app_cover_pic": "65f7ae7c0947ecd402160304",
                "max_chapter": "3",
                "max_media": "5",
                "duration_fmt": "2小时10分钟",
                "pic_url": "//img1.sycdn.imooc.com/65f7ae6f0932456505400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "中级",
                "media_total": "12"
            },
            {
                "id": "1415",
                "name": "徐老师带你 2小时 Flink SQL快速上手",
                "pic": "65f3b04c09f3131a05400304",
                "cat_id": "46",
                "duration": "7920",
                "teacher_id": "7861049",
                "start_time": "1710259200",
                "end_time": "1869580800",
                "create_time": "1710469222",
                "status": "3",
                "short_description": "带你快速学习，如何基于 Flink SQL快速解决企业中的实时计算难题",
                "description": "本课程针对Flink SQL内容进行讲解，主要涉及Flink SQL在实时计算中的典型应用场景和常见案例，帮助大家快速掌握基于Flink SQL的实时数据计算",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "了解Scala基础、Kafka基础和Flink基础，学习效果更佳",
                "purpose": "1：快速理解Flink SQL的执行原理；\r\n2：掌握Flink SQL的经典案例实战；\r\n3：掌握Flink SQL中静态表、动态表、版本表和时态表函数的应用；\r\n4：掌握Flink SQL中常见的数据类型。",
                "video_id": "0",
                "numbers": "563",
                "update_time": "1711614377",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "3",
                "teach_type": "2",
                "course_type": "3",
                "keyword": null,
                "finished": "0",
                "uid": "106515",
                "chapter_media": "3-1",
                "online_time": "1710473789",
                "blur_pic": "65f3b04d0001aec105400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "0",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover044",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "65f3b035093c517300000000",
                "app_cover_pic": "65f3b064094aabaa02160304",
                "max_chapter": "3",
                "max_media": "1",
                "duration_fmt": "2小时12分钟",
                "pic_url": "//img1.sycdn.imooc.com/65f3b04c09f3131a05400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "中级",
                "media_total": "12"
            },
            {
                "id": "1414",
                "name": "2小时极速入门脚手架开发",
                "pic": "65b3132a09276e7b05400304",
                "cat_id": "3",
                "duration": "10740",
                "teacher_id": "5953218",
                "start_time": "1706112000",
                "end_time": "1927555200",
                "create_time": "1706234678",
                "status": "3",
                "short_description": "极速入门Node脚手架开发，开发自己的提效工具",
                "description": "利用脚手架可以在实际工作中开发各类工具应用，提升工作效率。掌握脚手架开发，是前端工程师的必备技能。课程中，Sam老师将带领大家认识脚手架，并掌握如何开发一个基于Node.js的脚手架。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "本课程面向希望了解并快速入门脚手架开发的同学，需要具备Javascript基础和Node基础，课程中不会讲解这方面的基础知识",
                "purpose": "1. 学会Node脚手架实现原理\r\n2. 学会Node脚手架的开发流程\r\n2. 学会通过Node脚手架框架commander和yargs快速搭建脚手架",
                "video_id": "0",
                "numbers": "1542",
                "update_time": "1707186436",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "2",
                "teach_type": "2",
                "course_type": "2",
                "keyword": null,
                "finished": "0",
                "uid": "106515",
                "chapter_media": "2-13",
                "online_time": "1707186357",
                "blur_pic": "65b3132a00014d8505400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "0",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover044",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "65b3132f0978bd8805400304",
                "app_cover_pic": "65b31334090bcc5802160304",
                "max_chapter": "2",
                "max_media": "13",
                "duration_fmt": "2小时59分钟",
                "pic_url": "//img1.sycdn.imooc.com/65b3132a09276e7b05400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "初级",
                "media_total": "19"
            },
            {
                "id": "1413",
                "name": "MySQL数据库（下）-数据操作",
                "pic": "659deeaa093562bd05400304",
                "cat_id": "3",
                "duration": "7200",
                "teacher_id": "2084853",
                "start_time": "1704729600",
                "end_time": "1896019200",
                "create_time": "1704849081",
                "status": "3",
                "short_description": "带入进阶学习MySQL数据库。",
                "description": "本课程是MySQL数据库课程的其中一门，和MySQL数据库（上）组件了一门完整的MySQL数据库讲解。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "请先学习上一门《MySQL数据库（上）》",
                "purpose": "1、 表中数据的增删改操作\n2、 基础和 where 条件查询\n3、 排序和分页查询\n4、 聚合函数\n5、 分组和 having 条件查询\n6、 多表查询\n7、 多表查询举例\n8、 MySQL 预处理\n9、 在 Node.js 中使用 MySQL\n",
                "video_id": "0",
                "numbers": 1721,
                "update_time": "1710225863",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "1",
                "teach_type": "1",
                "course_type": "1",
                "keyword": null,
                "finished": "0",
                "uid": "2667037",
                "chapter_media": "2-2",
                "online_time": "1704936666",
                "blur_pic": "659e48a20001b5a205400304",
                "satisfied_score": "9.3",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "8.0",
                "comment_total": "4",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover036",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "659deea60934ff0a00000000",
                "app_cover_pic": "659deeb20924514702160304",
                "max_chapter": "2",
                "max_media": "2",
                "duration_fmt": "2小时",
                "pic_url": "//img1.sycdn.imooc.com/659deeaa093562bd05400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "入门",
                "media_total": "9"
            },
            {
                "id": "1412",
                "name": "MySQL数据库（上）- 基础入门",
                "pic": "659deb2b09bfc51805400304",
                "cat_id": "3",
                "duration": "7200",
                "teacher_id": "2084853",
                "start_time": "1704729600",
                "end_time": "1832860800",
                "create_time": "1704848188",
                "status": "3",
                "short_description": "带你入门MySQL数据库。",
                "description": "本课程讲解MySQL数据库基础入门，先讲解什么是MySQL，认识 SQL，以及MySQL 的安装、启动和连接，接着讲解数据库的增删改查，最后讲解 SQL 约束。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "对数据库感兴趣的所有人员都可学习。",
                "purpose": "1、 初识 MySQL\n2、 认识 SQL\n3、 MySQL 的安装、启动和连接\n4、 数据库的增删改查操作\n5、 SQL 数据类型\n6、 数据表的增删改查操作\n7、 SQL 约束\n8、 SQL 约束--外键约束\n",
                "video_id": "0",
                "numbers": "3165",
                "update_time": "1716581212",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "1",
                "teach_type": "1",
                "course_type": "1",
                "keyword": null,
                "finished": "0",
                "uid": "2667037",
                "chapter_media": "2-5",
                "online_time": "1704936635",
                "blur_pic": "659e45f60001b16c05400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "4",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover026",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "659deb1509add24d05400304",
                "app_cover_pic": "659deb310913716f02160304",
                "max_chapter": "2",
                "max_media": "5",
                "duration_fmt": "2小时",
                "pic_url": "//img1.sycdn.imooc.com/659deb2b09bfc51805400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "入门",
                "media_total": "8"
            },
            {
                "id": "1409",
                "name": "Express 基础入门",
                "pic": "659e41070956e5d105400304",
                "cat_id": "3",
                "duration": "7200",
                "teacher_id": "2084853",
                "start_time": "1698768000",
                "end_time": "1890662400",
                "create_time": "1698820395",
                "status": "3",
                "short_description": "带你快速入门 expres 及中间件！",
                "description": "课程分成三部分，基础篇讲解 Express 的基本使用方法，及中间件相关讲解，包括：App 级中间件的应用， Router 级中间件，Express 内置中间件，最后是第三方中间件，错误处理中间件。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "1、致少有一种语言开发经验\n2、会html、css等基本使用方法",
                "purpose": "1、Express 的基本用法\n2、Request 对象\n3、Response 对象\n4、响应动态页面\n5、路由开发\n6、 认识中间件\n7、 App 级中间件\n8、 App 级中间件的应用\n9、 Router 级中间件\n10、 Express 内置中间件\n11、 第三方中间件\n12、 错误处理中间件\n\n",
                "video_id": "0",
                "numbers": "1109",
                "update_time": "1713171231",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "1",
                "teach_type": "1",
                "course_type": "1",
                "keyword": null,
                "finished": "0",
                "uid": "2667037",
                "chapter_media": "3-1",
                "online_time": "1704936385",
                "blur_pic": "659e411c0001aa2705400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "4",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover001",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "659e411209fa51d905400304",
                "app_cover_pic": "659e412509310d2702160304",
                "max_chapter": "3",
                "max_media": "1",
                "duration_fmt": "2小时",
                "pic_url": "//img1.sycdn.imooc.com/659e41070956e5d105400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "入门",
                "media_total": "16"
            },
            {
                "id": "1410",
                "name": "Calcite数据管理与SQL优化实战",
                "pic": "6576b07109f97a2105400304",
                "cat_id": "46",
                "duration": "9780",
                "teacher_id": "5998157",
                "start_time": "1702051200",
                "end_time": "1988035200",
                "create_time": "1702277402",
                "status": "3",
                "short_description": "深入学习 Apache Calcite ，实践大数据计算引擎 SQL 解析、优化全流程。",
                "description": "SQL是编程领域最流行的语言之一，在当前多数据源、多数据计算引擎的环境下，Apache Calcite作为一个开源的数据管理工具，为SQL提供了更广泛、更灵活的应用场景。本门课程将和大家一起探索Calcite框架，了解Calcite的架构，实战SQL的解析和SQL的优化。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "了解SQL基本语法、了解Java编程基础，学习效果更佳",
                "purpose": "1.理解 Calcite 核心原理：了解 Calcite 架构和 Calcite 集成方式。\r\n2.实战 SQL 解析：使用 Calcite 进行 SQL 解析，并自定义数据源进行查询\r\n3.优化查询性能：了解 Calcite 查询重写、执行计划生成和 SQL 调优",
                "video_id": "0",
                "numbers": "941",
                "update_time": "1704781552",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "2",
                "teach_type": "2",
                "course_type": "1",
                "keyword": null,
                "finished": "0",
                "uid": "106515",
                "chapter_media": "3-5",
                "online_time": "1702349720",
                "blur_pic": "6576b072000179fc05400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "1",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover047",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "6576b07a09c9bc3c05400304",
                "app_cover_pic": "6576b07e09e4fc7b02160304",
                "max_chapter": "3",
                "max_media": "5",
                "duration_fmt": "2小时43分钟",
                "pic_url": "//img1.sycdn.imooc.com/6576b07109f97a2105400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "初级",
                "media_total": "15"
            },
            {
                "id": "1408",
                "name": "TypeScript极速入门",
                "pic": "6537777709c7e1be05400304",
                "cat_id": "3",
                "duration": "9540",
                "teacher_id": "2914210",
                "start_time": "1697472000",
                "end_time": "1790956800",
                "create_time": "1698033579",
                "status": "3",
                "short_description": "全面掌握实用的Typescript基础和高级用法，养成基于类型的编程思维模式。",
                "description": "课程分成三个部分，基础篇讲解 Typescript 的基本类型的使用，高级篇讲解高级类型的使用以及泛型的用法，最后从编程思想的角度去看类型系统和类型编程。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "掌握前 npm 包的使用，了解 JavaScript 基础，如果有面向对象开发经验，学习效果更佳",
                "purpose": "你能学到 Typescript 的基础概念、写法，类型的原理，以及在业务中真正实用的高级类型使用方法，更能通过泛型的学习，开启类型编程的大门。",
                "video_id": "0",
                "numbers": "3159",
                "update_time": "1708084320",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "2",
                "teach_type": "2",
                "course_type": "3",
                "keyword": null,
                "finished": "0",
                "uid": "106515",
                "chapter_media": "4-1",
                "online_time": "1698133906",
                "blur_pic": "653777780001817405400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "3",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover016",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "653777670946b43905400304",
                "app_cover_pic": "6537777d09a7d59702160304",
                "max_chapter": "4",
                "max_media": "1",
                "duration_fmt": "2小时39分钟",
                "pic_url": "//img1.sycdn.imooc.com/6537777709c7e1be05400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "初级",
                "media_total": "14"
            },
            {
                "id": "1405",
                "name": "LLM行业领军大佬 带你转型大语言模型-应对市场变革",
                "pic": "65153c91086f46f205400304",
                "cat_id": "63",
                "duration": "6600",
                "teacher_id": "11280240",
                "start_time": "1695657600",
                "end_time": "2042812800",
                "create_time": "1695872051",
                "status": "3",
                "short_description": "LLM行业领军大佬 带你转型大语言模型-应对市场变革\r\n",
                "description": "AI 改革浪潮下，（LLM）大语言模型已成为各大企业的迫切需求！这不仅是一种需求，更是一场竞争的关键。在全球范围内，企业们都在竞相寻找LLM领域的创新解决方案，以取得市场领先地位。\r\n\r\n现今的市场需求日益呈指数级增长，在AI 冲击和市场竞争激烈的双重职场压力中，掌握LLM领域的专业知识和技能，为个人提供崭新和好前景的职业机会，在激烈的市场竞争中脱颖而出，并为未来的职业发展提供强大的基础。\r\n\r\n现在正是抓住机会的最佳时机！加入LLM大语言模型的行列，让您在革命的浪潮中脱颖而出，成为市场需求的关键人才。别再等待，立即行动，抢占先机！\r\n《LLM大语言模型算法特训》课程：https://class.imooc.com/sale/llm\r\n",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "快速带你了解LLM大语言模型",
                "purpose": "快速了解LLM大语言模型进化路线和现状 \r\n分析企业对LLM人才的技术与能力需求\r\n解密大模型领域案例和行业榜单\r\n带你梳理大模型训练推理的职业发展路线\r\n",
                "video_id": "0",
                "numbers": "2426",
                "update_time": "1704781564",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "2",
                "teach_type": "1",
                "course_type": "1",
                "keyword": null,
                "finished": "0",
                "uid": "100120",
                "chapter_media": "1-5",
                "online_time": "1695895023",
                "blur_pic": "65153c910001c0be05400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "1",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover001",
                "add_croed_info": "\u003Cli\u003E扫码获取资料和优惠\u003C/li\u003E\u003Cli\u003E微信号：muke185999\u003C/li\u003E\u003Cli\u003E备注：大模型\u003C/li\u003E",
                "add_croed_qr": "652264ae088bb03e04300430",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "65153c91086f46f205400304",
                "app_cover_pic": "65153c9c08707eae02160304",
                "max_chapter": "1",
                "max_media": "5",
                "duration_fmt": "1小时50分钟",
                "pic_url": "//img1.sycdn.imooc.com/65153c91086f46f205400304-240-135.jpg",
                "update_in_24hours": false,
                "easy_name": "初级",
                "media_total": "5"
            },
            {
                "id": "1406",
                "name": "从Docker到K8S，容器技术演进之路",
                "pic": "651513cd08dd8e5b05400304",
                "cat_id": "46",
                "duration": "10920",
                "teacher_id": "6178050",
                "start_time": "1695744000",
                "end_time": "1916755200",
                "create_time": "1695880198",
                "status": "3",
                "short_description": "从Docker到Docker Compose再到Kubernetes 系统掌握容器技术的完整演进。",
                "description": "本课程旨在帮助同学入门和掌握容器技术的完整演进过程，重点聚焦在Docker、Docker Compose和Kubernetes这三个阶段。首先，我们将全面介绍Docker容器技术的基本概念、工作原理以及如何安装使用。其次，我们将探索Docker Compose，这是一个强大的容器编排工具，可以帮助在单主机上管理多个容器应用。最后，我们将深入学习Kubernetes（K8S），这是目前最受欢迎的容器编排平台之一，能够实现跨多个主机的容器自动化部署、扩展和管理。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "需要了解linux基本使用",
                "purpose": "1）零基础学习容器技术的完成演进，构建容器技术的知识体系。\r\n2）一个例子贯穿全套课程，平缓学习曲线，从单机到集群逐步层层递进学习容器技术与编排。\r\n3）学习Docker/dockerCompose/Kubernetes/Containerd的综合实践\r\n",
                "video_id": "0",
                "numbers": 3454,
                "update_time": "1713882204",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "2",
                "teach_type": "2",
                "course_type": "3",
                "keyword": null,
                "finished": "0",
                "uid": "106515",
                "chapter_media": "6-6",
                "online_time": "1695886243",
                "blur_pic": "651513cd0001a3a105400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "9",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover031",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "651513cd08dd8e5b05400304",
                "app_cover_pic": "651513d808d2583b02160304",
                "max_chapter": "6",
                "max_media": "6",
                "duration_fmt": "3小时2分钟",
                "pic_url": "//img1.sycdn.imooc.com/651513cd08dd8e5b05400304-240-135.jpg",
                "update_in_24hours": false,
                "easy_name": "初级",
                "media_total": "31"
            },
            {
                "id": "1351",
                "name": "全面解读大热行业 物联网/嵌入式前景与就业",
                "pic": "6504036108217d8705400304",
                "cat_id": "29",
                "duration": "2520",
                "teacher_id": "10772580,7019729",
                "start_time": "1694016000",
                "end_time": "1969804800",
                "create_time": "1694072940",
                "status": "3",
                "short_description": "全面解读大热行业 物联网/嵌入式前景与就业。",
                "description": "行业视角：物联网/嵌入式行业的未来趋势\r\n就业指南：了解最入式岗位分工与产品开发流程\r\n快速入门：如何系统学习嵌入式技术?\r\n干货放送：嵌入式工程师必备知识图谱",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "作为横跨工业与互联网的综合技术，近年来嵌入式越来越受到大家的关注，市场规模以肉眼可见的速度持续上涨。\r\n2022届秋招，以海康威视、大华、联发科为首的科技企业，甚至给应届生开出了高达40W甚至50W的薪资！远超其他技术岗位。",
                "purpose": "如果你有任何关于嵌入式新趋势、新技术的疑问，本课程都适合你。",
                "video_id": "0",
                "numbers": "1769",
                "update_time": "1710732169",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "1",
                "teach_type": "1",
                "course_type": "1",
                "keyword": null,
                "finished": "1",
                "uid": "3200030",
                "chapter_media": "1-13",
                "online_time": "1694762110",
                "blur_pic": "6504036200016ce705400304",
                "satisfied_score": "8.7",
                "ctype_one": "1",
                "ctype_one_score": "8.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "8.0",
                "comment_total": "1",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover037",
                "add_croed_info": "\u003Cli\u003E嵌入式体验课用于行业学习交流，课程咨询。\u003C/li\u003E",
                "add_croed_qr": "64f82aad08a7f0b809810939",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "6504036108217d8705400304",
                "app_cover_pic": "6504036c08c407c302160304",
                "max_chapter": "1",
                "max_media": "13",
                "duration_fmt": "42分钟",
                "pic_url": "//img1.sycdn.imooc.com/6504036108217d8705400304-240-135.jpg",
                "update_in_24hours": false,
                "easy_name": "入门",
                "media_total": "13"
            },
            {
                "id": "1402",
                "name": "《前端高级工程师》体验课",
                "pic": "64f6987f09c9707f05400304",
                "cat_id": "3",
                "duration": "21600",
                "teacher_id": "2432190",
                "start_time": "1693756800",
                "end_time": "2072534400",
                "create_time": "1693883242",
                "status": "3",
                "short_description": "深入探索前端工程师的职业技能提升之路",
                "description": "本课程将带领您踏上一段充满挑战与机遇的旅程，深入探索前端工程师的职业技能提升之路。我们将一同探索前端工程化、服务端开发与容器化的新领域，学习并掌握前端框架及开发技巧。同时，您也将理解并运用版本控制和自动化DevOps，提升工作效率，赋能自身。在这里，每一步的学习都将是一次跃升，每一次的挑战都将是一次机遇。让我们一起启航，探索前端的无限可能，迎接美好的未来。\r\n《高级前端工程师》体系课:\r\n全新打造“技术成长&职业破局”双高体系，深度打通“全栈 + 全流程 +多端+ 提效+AI赋能” ，递进式锤炼思维与高阶技能，高效实现能力跃迁助力成为“驾驭全局，深广兼备，打通多端全栈”的高级工程师。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "你可能有如下困境：\r\n1.缺乏大型复杂项目开发经验\r\n2.缺乏企业真实全流程、全栈开发经验\r\n3.缺乏对新技术（AI）等了解\r\n\r\n面向群体：\r\n1.希望摆脱现状，提升技术深广度，思维和实战能力，增加就业、涨薪机会\r\n2.有扎实前端技术基础，有项目经验，想更好就业，和进入更大平台",
                "purpose": "1. 掌握前端工程师的职业发展和技能提升路径\r\n2. 理解全面前端开发工作流程\r\n3. 了解紧跟市场的AI编程\r\n4. 深入前端UI库、跨端、移动端和大屏方案\r\n5. 了解自动化与工程化的技术路径\r\n6. 深入理解服务端渲染SSR、开发与容器化\r\n7. 帮助你理解和应用自动化和DevOps\r\n",
                "video_id": "0",
                "numbers": "2993",
                "update_time": "1693895087",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "4",
                "teach_type": "1",
                "course_type": "2",
                "keyword": null,
                "finished": "0",
                "uid": "100120",
                "chapter_media": "7-1",
                "online_time": "1693893474",
                "blur_pic": "64f698800001f2f905400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "0",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover001",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "64f6987f09c9707f00000000",
                "app_cover_pic": "64f6988e092b95e102160304",
                "max_chapter": "7",
                "max_media": "1",
                "duration_fmt": "6小时",
                "pic_url": "//img1.sycdn.imooc.com/64f6987f09c9707f05400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "高级",
                "media_total": "30"
            },
            {
                "id": "1397",
                "name": "《DBA数据库工程师》体验课",
                "pic": "64f56a3d096ed07405400304",
                "cat_id": "11",
                "duration": "17040",
                "teacher_id": "7248023",
                "start_time": "1692633600",
                "end_time": "1724169600",
                "create_time": "1692685745",
                "status": "3",
                "short_description": "本课程为慕课网《DBA数据库工程师》体系课程的体验课！",
                "description": "大数据时代数据量持续增长，数据库管理人员面临巨大缺口，在云数据库和大数据平台人才需求更是紧迫，本课程将从数据库基本入门到精通，并结合云时代和人工智能，让你构建完成的DBA知识体系，掌握DBA岗位的核心技能，课程中将大量生产实战进行落地，解决数据库实际生产问题，让你轻松胜任DBA岗位！\r\n",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "1、大数据时代，DBA工程师是企业经营与数据资产命脉的掌控者；\r\n2、DBA薪资高、就业机会多、发展空间大；\r\n3、应届生入行、技术转型、晋升涨薪的明智直选；\r\n4、课程设置多个学习阶段，助力你成为云时代抢手人才；",
                "purpose": "1、课程从基础到企业级项目实战，系统性讲解DBA工程师必备技能\r\n2、提升DBA必备核心能力（夯实数据库基础知识、提高MySQL进阶能力、扩展更多的DBA技能、掌握多种数据库优化场景、掌握多种高可用与自动化方案、企业项目实战与就业指导）\r\n3、多场景企业级项目实战落地能力",
                "video_id": "0",
                "numbers": "735",
                "update_time": "1693809482",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "1",
                "teach_type": "3",
                "course_type": "1",
                "keyword": null,
                "finished": "0",
                "uid": "9806685",
                "chapter_media": "1-18",
                "online_time": "1693806306",
                "blur_pic": "64f56cd10001235005400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "0",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover001",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "64f56a3d096ed07405400304",
                "app_cover_pic": "64f56a4609bdb5a002160304",
                "max_chapter": "1",
                "max_media": "18",
                "duration_fmt": "4小时44分钟",
                "pic_url": "//img1.sycdn.imooc.com/64f56a3d096ed07405400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "入门",
                "media_total": "18"
            },
            {
                "id": "1399",
                "name": "《大数据开发2023》体验课",
                "pic": "64f54cdb091b1e0105400304",
                "cat_id": "46",
                "duration": "8400",
                "teacher_id": "7861049",
                "start_time": "1692115200",
                "end_time": "1882800000",
                "create_time": "1692757198",
                "status": "3",
                "short_description": "本课程为慕课网《大数据工程师》体系课程的体验课。",
                "description": "百度搜索引擎的检索功能最核心的是实现了海量数据下多条件快速复杂查询的功能，目前在大数据领域中，Elasticsearch可以实现海量数据下的快速复杂查询，再借助于HBase的海量数据存储能力，二者结合到一起，可以轻松构建一套百度搜索引擎平台。本次体验课将由慕课网《大数据工程师》体系课程主讲老师带着大家一起构建一套属于你自己的百度搜索引擎。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "你是否有以下困惑：\r\n1、缺乏对大数据生态圈技术组件的系统了解\r\n2、掌握的技术不够全面，不够深入\r\n3、缺乏大数据技术架构设计能力\r\n4、缺乏大数据实战项目经验\r\n5、不知道如何快速切入，并且快速掌握大数据核心技能",
                "purpose": "体验课收获：\r\n1、了解大数据领域中常见的数据存储组件\r\n2、了解大数据领域中常见的数据分析引\r\n3、了解全文检索引擎在大数据行业中的应用\r\n4、掌握基于Elasticsearch和HBase如何构建百度搜索引擎\r\n5、了解《大数据工程师》体系课有哪些内容、特色与服务\r\n",
                "video_id": "0",
                "numbers": "1174",
                "update_time": "1693799185",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "1",
                "teach_type": "1",
                "course_type": "2",
                "keyword": null,
                "finished": "0",
                "uid": "106515",
                "chapter_media": "4-7",
                "online_time": "1693798778",
                "blur_pic": "64f54cdc00013be305400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "0",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover044",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "64f54cdb091b1e0105400304",
                "app_cover_pic": "64f54cf4097bc58b02160304",
                "max_chapter": "4",
                "max_media": "7",
                "duration_fmt": "2小时20分钟",
                "pic_url": "//img1.sycdn.imooc.com/64f54cdb091b1e0105400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "入门",
                "media_total": "12"
            },
            {
                "id": "1398",
                "name": "《产品经理》体验课",
                "pic": "64f54e1f093ff8e005400304",
                "cat_id": "16",
                "duration": "21600",
                "teacher_id": "9590022",
                "start_time": "1692633600",
                "end_time": "1853769600",
                "create_time": "1692685849",
                "status": "3",
                "short_description": "本课程为慕课网《产品经理》体验课。",
                "description": "慕课网《产品经理》介绍：\r\n这门课程是专为互联网人员打造的“产品核心能力”训练课程。无论你是大学应届生，想入行互联网做产品，或是程序员、测试，想转行做产品经理/想成为懂产品的工程师，都可以通过这门体系课，从0~1系统掌握产品全生命周期设计方法论，工具和项目实战经验。",
                "extra": null,
                "hits": "0",
                "istop": "0",
                "top_time": "0",
                "precondition": "如果你希望提升以下能力：\r\n1、课程面向大学应届生，想入行互联网做产品，或是程序员、测试，想转行做产品经理/想成为懂产品的工程师；\r\n2、本课程为《产品经理》体验课；\r\n3、不需要懂技术即可学习；",
                "purpose": "《产品经理》体验课收获：\r\n1、了解《产品经理》整体收获，特色与课程安排；\r\n2、了解互联网时代的特点和发展趋势；\r\n3、了解产品和产品经理的重要价值；\r\n4、了解如何进入产品经理这个行业；\r\n5、了解产品经理在团队中的重要角色；\r\n6、了解产品经理能力要求和岗位分工；",
                "video_id": "0",
                "numbers": "1490",
                "update_time": "1693798053",
                "company_id": "0",
                "company_courseid": "0",
                "easy_type": "1",
                "teach_type": "3",
                "course_type": "1",
                "keyword": null,
                "finished": "0",
                "uid": "3200030",
                "chapter_media": "4-7",
                "online_time": "1693798019",
                "blur_pic": "64f54e1f00019a5605400304",
                "satisfied_score": "10.0",
                "ctype_one": "1",
                "ctype_one_score": "10.0",
                "ctype_two": "2",
                "ctype_two_score": "10.0",
                "ctype_three": "3",
                "ctype_three_score": "10.0",
                "comment_total": "0",
                "seo_description": "",
                "seo_title": "",
                "background_pic": "cover011",
                "add_croed_info": "",
                "add_croed_qr": "",
                "is_bind_service": "0",
                "is_pay": "0",
                "user_course_show": "0",
                "pic2": "64f54e1f093ff8e005400304",
                "app_cover_pic": "64f54e2d0911d77002160304",
                "max_chapter": "4",
                "max_media": "7",
                "duration_fmt": "6小时",
                "pic_url": "//img1.sycdn.imooc.com/64f54e1f093ff8e005400304-240-135.png",
                "update_in_24hours": false,
                "easy_name": "入门",
                "media_total": "17"
            }
        ],


        scrollTop: 0,
        scrollHeight: 0
    },
    onLoad: function () {
        //  这里要注意，微信的scroll-view必须要设置高度才能监听滚动事件，所以，需要在页面的onLoad事件中给scroll-view的高度赋值
        var that = this;
        wx.getSystemInfo({
            success: function (res) {
                that.setData({
                    scrollHeight: res.windowHeight
                });
            }
        });
        // loadMore(that);
    },
    //页面滑动到底部
    bindDownLoad: function () {
        var that = this;
        // loadMore(that);
        console.log("lower");
    },
    scroll: function (event) {
        //该方法绑定了页面滚动时的事件，我这里记录了当前的position.y的值,为了请求数据之后把页面定位到这里来。
        this.setData({
            scrollTop: event.detail.scrollTop
        });
    },
    topLoad: function (event) {
        //  该方法绑定了页面滑动到顶部的事件，然后做上拉刷新
        // page = 0;
        // this.setData({
        //     list: [],
        //     scrollTop: 0
        // });
        // loadMore(this);
        console.log("topLoad");
    }
})